package com.xuezk.study.mapper;

import java.util.Date;

public class MemberInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.create_date
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.id_card
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.insure_no
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private String insureNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.mobile
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.name
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.id
     *
     * @return the value of member_info.id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.id
     *
     * @param id the value for member_info.id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.create_date
     *
     * @return the value of member_info.create_date
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.create_date
     *
     * @param createDate the value for member_info.create_date
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.id_card
     *
     * @return the value of member_info.id_card
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.id_card
     *
     * @param idCard the value for member_info.id_card
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.insure_no
     *
     * @return the value of member_info.insure_no
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public String getInsureNo() {
        return insureNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.insure_no
     *
     * @param insureNo the value for member_info.insure_no
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setInsureNo(String insureNo) {
        this.insureNo = insureNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.mobile
     *
     * @return the value of member_info.mobile
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.mobile
     *
     * @param mobile the value for member_info.mobile
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.name
     *
     * @return the value of member_info.name
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.name
     *
     * @param name the value for member_info.name
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}