package com.xuezk.study.mapper;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.member_id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_no
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.member_info_id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    private Long memberInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.member_id
     *
     * @return the value of order_info.member_id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.member_id
     *
     * @param memberId the value for order_info.member_id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_no
     *
     * @return the value of order_info.order_no
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_no
     *
     * @param orderNo the value for order_info.order_no
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.member_info_id
     *
     * @return the value of order_info.member_info_id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public Long getMemberInfoId() {
        return memberInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.member_info_id
     *
     * @param memberInfoId the value for order_info.member_info_id
     *
     * @mbg.generated Wed Nov 20 20:16:07 CST 2019
     */
    public void setMemberInfoId(Long memberInfoId) {
        this.memberInfoId = memberInfoId;
    }
}